# Generated by Django 4.0.1 on 2022-01-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_book_options_alter_book_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
